<?php
$categories = [
    ['CFPM - Grau Mitjà', 0],
    ['CFPS - Grau Superior', 0],
    
    ['AF - Arts Gràfiques', 1],
    ['AF10 - Preimpressió digital', 3],
    ['AF20 - Impressió gràfica', 3],
    ['AF21 - Impressió gràfica (converting)', 3],
    ['AF30 - Postimpressió i acabats gràfics', 3],
    
    ['AG - Administració i Gestió', 1],
    ['AG10 - Gestió administrativa', 8],
    ['AG11 - Gestió administrativa (àmbit jurídic)', 8],
    ['AG12 - Gestió administrativa (àmbit sanitari)', 8],
    
    ['AR - Agraria', 1],
    ['AR10 - Producció agropecuària', 12],
    ['AR11 - Producció agropecuària (Producció agrícola)', 12],
    ['AR12 - Producció agropecuària (Producció ramadera)', 12],
    ['AR20 - Producció agroecològica', 12],
    ['AR21 - Producció agroecològica (Producció agrícola ecològica)', 12],
    ['AR22 - Producció agroecològica (Producció ramadera ecològica)', 12],
    ['AR30 - Aprofitament i conservació del medi natural', 12],
    ['AR50 - Jardineria i floristeria', 12],
    ['AR60 - Activitats eqüestres', 12],
    
    ['CM - Comerç i Màrqueting', 1],
    ['CM10 - Activitats comercials', 22],
    ['CM11 - Activitats comercials (productes frescos)', 22],
    ['CM12 - Activitats comercials (logística)', 22],
    ['CM13 - Activitats comercials (moda)', 22],
    
    ['EA - Energia i Aigua', 1],
    ['EA10 - Xarxes, instal·lacions i estacions de tractament d\'aigua', 27],
    ['EA20 - Xarxes i estacions de tractament d\'aigües', 27],
    
    ['EE - Electricitat i Electrònica', 1],
    ['EE10 - Instal·lacions elèctriques i automàtiques', 30],
    ['EE30 - Instal·lacions de telecomunicacions', 30],
    
    ['EO - Edificació i Obra Civil', 1],
    ['EO10 - Obres d\'interior, decoració i rehabilitació', 33],
    ['EO20 - Construcció', 33],
    
    ['FM - Fabricació Mecànica', 1],
    ['FM10 - Soldadura i caldereria', 36],
    ['FM20 - Mecanització', 36],
    ['FM21 - Mecanització (Manteniment i reparació en rellotgeria)', 36],
    
    ['FS - Fusta i Moble', 1],
    ['FS10 - Fusteria i moble', 40],
    ['FS20 - Instal·lació i moblament', 40],
    
    ['HT - Hostaleria i Turisme', 1],
    ['HT10 - Cuina i gastronomia', 43],
    ['HT30 - Serveis en restauració', 43],
    
    ['IA - Indústries Alimentàries', 1],
    ['IA10 - Elaboració de productes alimentaris', 46],
    ['IA30 - Olis d\'oliva i vins', 46],
    ['IA60 - Forneria, pastisseria i confiteria', 46],
    
    ['IC - Informàtica i Comunicacions', 1],
    ['IC10 - Sistemes microinformàtics i xarxes', 50],
    
    ['IE - Indústries Extractives', 1],
    ['IE10 - Excavacions i sondatges', 52],
    ['IE11 - Excavacions i sondatges (operacions de maquinària de construcció)', 52],
    ['IE20 - Pedra natural', 52],
    
    ['IM - Instal·lació i Manteniment', 1],
    ['IM10 - Manteniment electromecànic', 56],
    ['IM11 - Manteniment electromecànic (vaixells d\'esbarjo i serveis portuaris)', 56],
    ['IM20 - Instal·lacions de producció de calor', 56],
    ['IM30 - Instal·lacions frigorífiques i de climatització', 56],
    
    ['IP - Imatge Personal', 1],
    ['IP10 - Perruqueria i cosmètica capil·lar', 61],
    ['IP20 - Estètica i bellesa', 61],
    
    ['IS - Imatge i So', 1],
    ['IS10 - Vídeo, discjòquei i so', 64],
    
    ['MP - Marítim-Pesquera', 1],
    ['MP10 - Cultius Aqüícoles', 66],
    ['MP20 - Operacions subaquàtiques i hiperbàriques', 66],
    ['MP30 - Navegació i pesca de litoral', 66],
    ['MP40 - Manteniment i control de la maquinària de vaixells i embarcacions', 66],
    
    ['QU - Química', 1],
    ['QU10 - Planta química', 71],
    ['QU11 - Planta química (productes farmacèutics i cosmètics)', 71],
    ['QU20 - Operacions de laboratori', 71],
    
    ['SA - Sanitat', 1],
    ['SA20 - Farmàcia i parafarmàcia', 75],
    ['SA30 - Emergències sanitàries', 75],
    
    ['SC - Serveis Socioculturals', 1],
    ['SC10 - Atenció a persones en situació de dependència', 78],
    
    ['SM - Seguretat i Medi Ambient', 1],
    ['SM20 - Emergències i protecció civil', 80],
    
    ['TM - Transport i Manteniment de Vehicles', 1],
    ['TM10 - Electromecànica de vehicles automòbils', 82],
    ['TM11 - Electromecànica de vehicles automòbils (Avions amb motor de pistó)', 82],
    ['TM12 - Electromecànica de vehicles automòbils (Electromecánica de vehicles industrials)', 82],
    ['TM20 - Carrosseria', 82],
    ['TM30 - Electromecànica de maquinària', 82],
    ['TM40 - Manteniment de material rodant ferroviari', 82],
    ['TM50 - Conducció de vehicles de transport per carretera', 82],
    ['TM60 - Manteniment d\'embarcacions d\'esbarjo', 82],
    
    ['TX - Tèxtil i Confecció', 1],
    ['TX10 - Fabricació i ennobliment de productes tèxtils', 91],
    ['TX11 - Fabricació i ennobliment de productes tèxtils (gèneres de punt)', 91],
    ['TX50 - Confecció i moda', 91],
    ['TX51 - Confecció i moda (innovació i producció de la moda)', 91],
    
    ['AE - Activitats Físiques i Esportives', 2],
    ['AEA0 - Ensenyament i animació socioesportiva', 96],
    ['AEB0 - Condicionament físic', 96],
    
    ['AF - Arts Gràfiques', 2],
    ['AFA0 - Disseny i edició de publicacions impreses i multimèdia', 99],
    ['AFB0 - Disseny i gestió de la producció gràfica', 99],
    
    ['AG - Administració i Gestió', 2],
    ['AGA0 - Assistència a la direcció', 102],
    ['AGB0 - Administració i finances', 102],
    ['AGB1 - Administració i finances (gestor d\'assegurances)', 102],
    
    ['AR - Agraria', 2],
    ['ARA0 - Gestió forestal i del medi natural', 106],
    ['ARB0 - Paisatgisme i medi rural', 106],
    ['ARB1 - Paisatgisme i medi rural (gestió agropecuària)', 106],
    ['ARC0 - Ramaderia i assistència en sanitat animal', 106],
    
    ['CM - Comerç i Màrqueting', 2],
    ['CMA0 - Gestió de vendes i espais comercials', 111],
    ['CMB0 - Comerç internacional', 111],
    ['CMC0 - Transport i logística', 111],
    ['CMD0 - Màrqueting i publicitat', 111],
    ['CMD1 - Màrqueting i publicitat (enològic)', 111],
    ['CMD2 - Màrqueting i publicitat (promoció turística)', 111],
    
    ['EA - Energia i Aigua', 2],
    ['EAA0 - Eficiència energètica i energia solar tèrmica', 118],
    ['EAC0 - Energies renovables', 118],
    ['EAD0 - Gestió de l\'aigua', 118],
    
    ['EE - Electricitat i Electrònica', 2],
    ['EEA0 - Sistemes electrotècnics i automatitzats', 122],
    ['EEA1 - Sistemes electrotècnics i automatitzats (instal·lacions elèctriques i comunicacions del vaixell)', 122],
    ['EEB0 - Automatització i robòtica industrial', 122],
    ['EEC0 - Manteniment electrònic', 122],
    ['EED0 - Sistemes de telecomunicacions i informàtics', 122],
    ['EEE0 - Electromedicina clínica', 122],
    
    ['EO - Edificació i Obra Civil', 2],
    ['EOA0 - Projectes d\'obra civil', 129],
    ['EOA1 - Projectes d\'obra civil (Sobrestants)', 129],
    ['EOA2 - Projectes d\'obra civil (ús d\'aplicacions SIG)', 129],
    ['EOB0 - Projectes d\'edificació', 129],
    ['EOB1 - Projectes d\'edificació (rehabilitació i restauració)', 129],
    ['EOC0 - Organització i control d\'obres de construcció', 129],
    
    ['FM - Fabricació Mecànica', 2],
    ['FMA0 - Construccions metàl·liques', 136],
    ['FMB0 - Programació de la producció en fabricació mecànica', 136],
    ['FMB1 - Programació de la producció en fabricació mecànica (motlles i matrius)', 136],
    ['FMC0 - Disseny en fabricació mecànica', 136],
    ['FMC1 - Disseny en fabricació mecànica (desenvolupament virtual de l\'automòbil)', 136],
    ['FMD0 - Programació de la producció en emmotllament de metalls i polímers', 136],
    
    ['FS - Fusta i Moble', 2],
    ['FSA0 - Disseny i moblament', 143],
    ['FSA1 - Disseny i moblament (construccions efímeres i decorats)', 143],
    
    ['HT - Hostaleria i Turisme', 2],
    ['HTA0 - Agències de viatges i gestió d\'esdeveniments', 146],
    ['HTB0 - Gestió d\'allotjaments turístics', 146],
    ['HTD0 - Direcció de cuina', 146],
    ['HTE0 - Direcció de serveis en restauració', 146],
    ['HTF0 - Guia, informació i assistència turístiques', 146],
    ['HTF1 - Guia, informació i assistència turístiques (animació turística)', 146],
    
    ['IA - Indústries Alimentàries', 2],
    ['IAA0 - Vitivinicultura', 153],
    ['IAB0 - Processos i qualitat en la indústria alimentària', 153],
    
    ['IC - Informàtica i Comunicacions', 2],
    ['ICA0 - Administració de sistemes informàtics en xarxa', 156],
    ['ICA1 - Administració de sistemes informàtics en xarxa (ciberseguretat)', 156],
    ['ICB0 - Desenvolupament d\'aplicacions multiplataforma', 156],
    ['ICB1 - Desenvolupament d\'aplicacions multiplataforma (informàtica aplicada a la logística)', 156],
    ['ICB2 - Desenvolupament d\'aplicacions multiplataforma (videojocs i oci digital)', 156],
    ['ICC0 - Desenvolupament d\'aplicacions web', 156],
    ['ICC1 - Desenvolupament d\'aplicacions web (bioinformàtica)', 156],
    
    ['IM - Instal·lació i Manteniment', 2],
    ['IMA0 - Manteniment d\'instal·lacions tèrmiques i de fluids', 164],
    ['IMB0 - Desenvolupament de projectes d\'instal·lacions tèrmiques i de fluids', 164],
    ['IMC0 - Mecatrònica industrial', 164],
    ['IMC1 - Mecatrònica industrial (fabricació de productes ceràmics)', 164],
    
    ['IP - Imatge Personal', 2],
    ['IPA0 - Assessoria d\'imatge personal i corporativa', 169],
    ['IPB0 - Estètica integral i benestar', 169],
    ['IPC0 - Estilisme i direcció de perruqueria', 169],
    ['IPD0 - Caracterització i maquillatge professional', 169],
    
    ['IS - Imatge i So', 2],
    ['ISA0 - Realització de projectes d\'audiovisuals i espectacles', 174],
    ['ISB0 - Il·luminació, captació i tractament d\'imatge', 174],
    ['ISC0 - So per a audiovisuals i espectacles', 174],
    ['ISD0 - Producció d\'audiovisuals i espectacles', 174],
    ['ISE0 - Animacions 3D, jocs i entorns interactius', 174],
    ['ISE1 - Animacions 3D, jocs i entorns interactius (móns virtuals, realitat augmentada i gamificació)', 174],
    
    ['MP - Marítim-Pesquera', 2],
    ['MPA0 - Transport marítim i pesca d\'altura', 181],
    ['MPB0 - Aqüicultura', 181],
    ['MPC0 - Organització del manteniment de la maquinària de vaixells i embarcacions', 181],
    
    ['QU - Química', 2],
    ['QUA0 - Química industrial', 185],
    ['QUB0 - Fabricació de productes farmacèutics, biotecnològics i afins', 185],
    ['QUD0 - Laboratori d\'anàlisi i control de qualitat', 185],
    
    ['SA - Sanitat', 2],
    ['SAA0 - Pròtesis dentals', 189],
    ['SAB0 - Ortopròtesi i productes de suport', 189],
    ['SAC0 - Anatomia patològica i citodiagnòstic', 189],
    ['SAD0 - Documentació i administració sanitària', 189],
    ['SAD1 - Documentació i administració sanitàries (gestió de dades)', 189],
    ['SAE0 - Laboratori clínic i biomèdic', 189],
    ['SAE1 - Laboratori clínic i biomèdic (recerca)', 189],
    ['SAF0 - Radioteràpia i dosimetria', 189],
    ['SAG0 - Audiologia protètica', 189],
    ['SAH0 - Higiene bucodental', 189],
    ['SAI0 - Imatge per al diagnòstic i medicina nuclear', 189],
    
    ['SC - Serveis Socioculturals', 2],
    ['SCA0 - Animació sociocultural i turística', 201],
    ['SCB0 - Educació Infantil', 201],
    ['SCC0 - Integració social', 201],
    ['SCD0 - Promoció d\'igualtat de gènere', 201],
    ['SCE0 - Mediació comunicativa', 201],
    
    ['SM - Seguretat i Medi Ambient', 2],
    ['SMA0 - Educació i control ambiental', 207],
    ['SMB0 - Coordinació d\'emergències i protecció civil', 207],
    
    ['TM - Transport i Manteniment de Vehicles', 2],
    ['TMA0 - Automoció', 210],
    ['TMA1 - Automoció (Vehicles industrials)', 210],
    
    ['TX - Tèxtil i Confecció', 2],
    ['TXA0 - Disseny tècnic en tèxtil i pell', 213],
    ['TXB0 - Vestuari a mida i d\'espectacles', 213],
    ['TXE0 - Patronatge i moda', 213]
];