<?php
$categories = [
    ['name' => 'CFPM - Grau Mitjà', 'parent_id' => 0],
    ['name' => 'CFPS - Grau Superior', 'parent_id' => 0],
    
    ['name' => 'AF - Arts Gràfiques', 'parent_id' => 1],
    ['name' => 'AF10 - Preimpressió digital', 'parent_id' => 3],
    ['name' => 'AF20 - Impressió gràfica', 'parent_id' => 3],
    ['name' => 'AF21 - Impressió gràfica (converting)', 'parent_id' => 3],
    ['name' => 'AF30 - Postimpressió i acabats gràfics', 'parent_id' => 3],
    
    ['name' => 'AG - Administració i Gestió', 'parent_id' => 1],
    ['name' => 'AG10 - Gestió administrativa', 'parent_id' => 8],
    ['name' => 'AG11 - Gestió administrativa (àmbit jurídic)', 'parent_id' => 8],
    ['name' => 'AG12 - Gestió administrativa (àmbit sanitari)', 'parent_id' => 8],
    
    ['name' => 'AR - Agraria', 'parent_id' => 1],
    ['name' => 'AR10 - Producció agropecuària', 'parent_id' => 12],
    ['name' => 'AR11 - Producció agropecuària (Producció agrícola)', 'parent_id' => 12],
    ['name' => 'AR12 - Producció agropecuària (Producció ramadera)', 'parent_id' => 12],
    ['name' => 'AR20 - Producció agroecològica', 'parent_id' => 12],
    ['name' => 'AR21 - Producció agroecològica (Producció agrícola ecològica)', 'parent_id' => 12],
    ['name' => 'AR22 - Producció agroecològica (Producció ramadera ecològica)', 'parent_id' => 12],
    ['name' => 'AR30 - Aprofitament i conservació del medi natural', 'parent_id' => 12],
    ['name' => 'AR50 - Jardineria i floristeria', 'parent_id' => 12],
    ['name' => 'AR60 - Activitats eqüestres', 'parent_id' => 12],
    
    ['name' => 'CM - Comerç i Màrqueting', 'parent_id' => 1],
    ['name' => 'CM10 - Activitats comercials', 'parent_id' => 22],
    ['name' => 'CM11 - Activitats comercials (productes frescos)', 'parent_id' => 22],
    ['name' => 'CM12 - Activitats comercials (logística)', 'parent_id' => 22],
    ['name' => 'CM13 - Activitats comercials (moda)', 'parent_id' => 22],
    
    ['name' => 'EA - Energia i Aigua', 'parent_id' => 1],
    ['name' => 'EA10 - Xarxes, instal·lacions i estacions de tractament d\'aigua', 'parent_id' => 27],
    ['name' => 'EA20 - Xarxes i estacions de tractament d\'aigües', 'parent_id' => 27],
    
    ['name' => 'EE - Electricitat i Electrònica', 'parent_id' => 1],
    ['name' => 'EE10 - Instal·lacions elèctriques i automàtiques', 'parent_id' => 30],
    ['name' => 'EE30 - Instal·lacions de telecomunicacions', 'parent_id' => 30],
    
    ['name' => 'EO - Edificació i Obra Civil', 'parent_id' => 1],
    ['name' => 'EO10 - Obres d\'interior, decoració i rehabilitació', 'parent_id' => 33],
    ['name' => 'EO20 - Construcció', 'parent_id' => 33],
    
    ['name' => 'FM - Fabricació Mecànica', 'parent_id' => 1],
    ['name' => 'FM10 - Soldadura i caldereria', 'parent_id' => 36],
    ['name' => 'FM20 - Mecanització', 'parent_id' => 36],
    ['name' => 'FM21 - Mecanització (Manteniment i reparació en rellotgeria)', 'parent_id' => 36],
    
    ['name' => 'FS - Fusta i Moble', 'parent_id' => 1],
    ['name' => 'FS10 - Fusteria i moble', 'parent_id' => 40],
    ['name' => 'FS20 - Instal·lació i moblament', 'parent_id' => 40],
    
    ['name' => 'HT - Hostaleria i Turisme', 'parent_id' => 1],
    ['name' => 'HT10 - Cuina i gastronomia', 'parent_id' => 43],
    ['name' => 'HT30 - Serveis en restauració', 'parent_id' => 43],
    
    ['name' => 'IA - Indústries Alimentàries', 'parent_id' => 1],
    ['name' => 'IA10 - Elaboració de productes alimentaris', 'parent_id' => 46],
    ['name' => 'IA30 - Olis d\'oliva i vins', 'parent_id' => 46],
    ['name' => 'IA60 - Forneria, pastisseria i confiteria', 'parent_id' => 46],
    
    ['name' => 'IC - Informàtica i Comunicacions', 'parent_id' => 1],
    ['name' => 'IC10 - Sistemes microinformàtics i xarxes', 'parent_id' => 50],
    
    ['name' => 'IE - Indústries Extractives', 'parent_id' => 1],
    ['name' => 'IE10 - Excavacions i sondatges', 'parent_id' => 52],
    ['name' => 'IE11 - Excavacions i sondatges (operacions de maquinària de construcció)', 'parent_id' => 52],
    ['name' => 'IE20 - Pedra natural', 'parent_id' => 52],
    
    ['name' => 'IM - Instal·lació i Manteniment', 'parent_id' => 1],
    ['name' => 'IM10 - Manteniment electromecànic', 'parent_id' => 56],
    ['name' => 'IM11 - Manteniment electromecànic (vaixells d\'esbarjo i serveis portuaris)', 'parent_id' => 56],
    ['name' => 'IM20 - Instal·lacions de producció de calor', 'parent_id' => 56],
    ['name' => 'IM30 - Instal·lacions frigorífiques i de climatització', 'parent_id' => 56],
    
    ['name' => 'IP - Imatge Personal', 'parent_id' => 1],
    ['name' => 'IP10 - Perruqueria i cosmètica capil·lar', 'parent_id' => 61],
    ['name' => 'IP20 - Estètica i bellesa', 'parent_id' => 61],
    
    ['name' => 'IS - Imatge i So', 'parent_id' => 1],
    ['name' => 'IS10 - Vídeo, discjòquei i so', 'parent_id' => 64],
    
    ['name' => 'MP - Marítim-Pesquera', 'parent_id' => 1],
    ['name' => 'MP10 - Cultius Aqüícoles', 'parent_id' => 66],
    ['name' => 'MP20 - Operacions subaquàtiques i hiperbàriques', 'parent_id' => 66],
    ['name' => 'MP30 - Navegació i pesca de litoral', 'parent_id' => 66],
    ['name' => 'MP40 - Manteniment i control de la maquinària de vaixells i embarcacions', 'parent_id' => 66],
    
    ['name' => 'QU - Química', 'parent_id' => 1],
    ['name' => 'QU10 - Planta química', 'parent_id' => 71],
    ['name' => 'QU11 - Planta química (productes farmacèutics i cosmètics)', 'parent_id' => 71],
    ['name' => 'QU20 - Operacions de laboratori', 'parent_id' => 71],
    
    ['name' => 'SA - Sanitat', 'parent_id' => 1],
    ['name' => 'SA20 - Farmàcia i parafarmàcia', 'parent_id' => 75],
    ['name' => 'SA30 - Emergències sanitàries', 'parent_id' => 75],
    
    ['name' => 'SC - Serveis Socioculturals', 'parent_id' => 1],
    ['name' => 'SC10 - Atenció a persones en situació de dependència', 'parent_id' => 78],
    
    ['name' => 'SM - Seguretat i Medi Ambient', 'parent_id' => 1],
    ['name' => 'SM20 - Emergències i protecció civil', 'parent_id' => 80],
    
    ['name' => 'TM - Transport i Manteniment de Vehicles', 'parent_id' => 1],
    ['name' => 'TM10 - Electromecànica de vehicles automòbils', 'parent_id' => 82],
    ['name' => 'TM11 - Electromecànica de vehicles automòbils (Avions amb motor de pistó)', 'parent_id' => 82],
    ['name' => 'TM12 - Electromecànica de vehicles automòbils (Electromecánica de vehicles industrials)', 'parent_id' => 82],
    ['name' => 'TM20 - Carrosseria', 'parent_id' => 82],
    ['name' => 'TM30 - Electromecànica de maquinària', 'parent_id' => 82],
    ['name' => 'TM40 - Manteniment de material rodant ferroviari', 'parent_id' => 82],
    ['name' => 'TM50 - Conducció de vehicles de transport per carretera', 'parent_id' => 82],
    ['name' => 'TM60 - Manteniment d\'embarcacions d\'esbarjo', 'parent_id' => 82],
    
    ['name' => 'TX - Tèxtil i Confecció', 'parent_id' => 1],
    ['name' => 'TX10 - Fabricació i ennobliment de productes tèxtils', 'parent_id' => 91],
    ['name' => 'TX11 - Fabricació i ennobliment de productes tèxtils (gèneres de punt)', 'parent_id' => 91],
    ['name' => 'TX50 - Confecció i moda', 'parent_id' => 91],
    ['name' => 'TX51 - Confecció i moda (innovació i producció de la moda)', 'parent_id' => 91],
    
    ['name' => 'AE - Activitats Físiques i Esportives', 'parent_id' => 2],
    ['name' => 'AEA0 - Ensenyament i animació socioesportiva', 'parent_id' => 96],
    ['name' => 'AEB0 - Condicionament físic', 'parent_id' => 96],
    
    ['name' => 'AF - Arts Gràfiques', 'parent_id' => 2],
    ['name' => 'AFA0 - Disseny i edició de publicacions impreses i multimèdia', 'parent_id' => 99],
    ['name' => 'AFB0 - Disseny i gestió de la producció gràfica', 'parent_id' => 99],
    
    ['name' => 'AG - Administració i Gestió', 'parent_id' => 2],
    ['name' => 'AGA0 - Assistència a la direcció', 'parent_id' => 102],
    ['name' => 'AGB0 - Administració i finances', 'parent_id' => 102],
    ['name' => 'AGB1 - Administració i finances (gestor d\'assegurances)', 'parent_id' => 102],
    
    ['name' => 'AR - Agraria', 'parent_id' => 2],
    ['name' => 'ARA0 - Gestió forestal i del medi natural', 'parent_id' => 106],
    ['name' => 'ARB0 - Paisatgisme i medi rural', 'parent_id' => 106],
    ['name' => 'ARB1 - Paisatgisme i medi rural (gestió agropecuària)', 'parent_id' => 106],
    ['name' => 'ARC0 - Ramaderia i assistència en sanitat animal', 'parent_id' => 106],
    
    ['name' => 'CM - Comerç i Màrqueting', 'parent_id' => 2],
    ['name' => 'CMA0 - Gestió de vendes i espais comercials', 'parent_id' => 111],
    ['name' => 'CMB0 - Comerç internacional', 'parent_id' => 111],
    ['name' => 'CMC0 - Transport i logística', 'parent_id' => 111],
    ['name' => 'CMD0 - Màrqueting i publicitat', 'parent_id' => 111],
    ['name' => 'CMD1 - Màrqueting i publicitat (enològic)', 'parent_id' => 111],
    ['name' => 'CMD2 - Màrqueting i publicitat (promoció turística)', 'parent_id' => 111],
    
    ['name' => 'EA - Energia i Aigua', 'parent_id' => 2],
    ['name' => 'EAA0 - Eficiència energètica i energia solar tèrmica', 'parent_id' => 118],
    ['name' => 'EAC0 - Energies renovables', 'parent_id' => 118],
    ['name' => 'EAD0 - Gestió de l\'aigua', 'parent_id' => 118],
    
    ['name' => 'EE - Electricitat i Electrònica', 'parent_id' => 2],
    ['name' => 'EEA0 - Sistemes electrotècnics i automatitzats', 'parent_id' => 122],
    ['name' => 'EEA1 - Sistemes electrotècnics i automatitzats (instal·lacions elèctriques i comunicacions del vaixell)', 'parent_id' => 122],
    ['name' => 'EEB0 - Automatització i robòtica industrial', 'parent_id' => 122],
    ['name' => 'EEC0 - Manteniment electrònic', 'parent_id' => 122],
    ['name' => 'EED0 - Sistemes de telecomunicacions i informàtics', 'parent_id' => 122],
    ['name' => 'EEE0 - Electromedicina clínica', 'parent_id' => 122],
    
    ['name' => 'EO - Edificació i Obra Civil', 'parent_id' => 2],
    ['name' => 'EOA0 - Projectes d\'obra civil', 'parent_id' => 129],
    ['name' => 'EOA1 - Projectes d\'obra civil (Sobrestants)', 'parent_id' => 129],
    ['name' => 'EOA2 - Projectes d\'obra civil (ús d\'aplicacions SIG)', 'parent_id' => 129],
    ['name' => 'EOB0 - Projectes d\'edificació', 'parent_id' => 129],
    ['name' => 'EOB1 - Projectes d\'edificació (rehabilitació i restauració)', 'parent_id' => 129],
    ['name' => 'EOC0 - Organització i control d\'obres de construcció', 'parent_id' => 129],
    
    ['name' => 'FM - Fabricació Mecànica', 'parent_id' => 2],
    ['name' => 'FMA0 - Construccions metàl·liques', 'parent_id' => 136],
    ['name' => 'FMB0 - Programació de la producció en fabricació mecànica', 'parent_id' => 136],
    ['name' => 'FMB1 - Programació de la producció en fabricació mecànica (motlles i matrius)', 'parent_id' => 136],
    ['name' => 'FMC0 - Disseny en fabricació mecànica', 'parent_id' => 136],
    ['name' => 'FMC1 - Disseny en fabricació mecànica (desenvolupament virtual de l\'automòbil)', 'parent_id' => 136],
    ['name' => 'FMD0 - Programació de la producció en emmotllament de metalls i polímers', 'parent_id' => 136],
    
    ['name' => 'FS - Fusta i Moble', 'parent_id' => 2],
    ['name' => 'FSA0 - Disseny i moblament', 'parent_id' => 143],
    ['name' => 'FSA1 - Disseny i moblament (construccions efímeres i decorats)', 'parent_id' => 143],
    
    ['name' => 'HT - Hostaleria i Turisme', 'parent_id' => 2],
    ['name' => 'HTA0 - Agències de viatges i gestió d\'esdeveniments', 'parent_id' => 146],
    ['name' => 'HTB0 - Gestió d\'allotjaments turístics', 'parent_id' => 146],
    ['name' => 'HTD0 - Direcció de cuina', 'parent_id' => 146],
    ['name' => 'HTE0 - Direcció de serveis en restauració', 'parent_id' => 146],
    ['name' => 'HTF0 - Guia, informació i assistència turístiques', 'parent_id' => 146],
    ['name' => 'HTF1 - Guia, informació i assistència turístiques (animació turística)', 'parent_id' => 146],
    
    ['name' => 'IA - Indústries Alimentàries', 'parent_id' => 2],
    ['name' => 'IAA0 - Vitivinicultura', 'parent_id' => 153],
    ['name' => 'IAB0 - Processos i qualitat en la indústria alimentària', 'parent_id' => 153],
    
    ['name' => 'IC - Informàtica i Comunicacions', 'parent_id' => 2],
    ['name' => 'ICA0 - Administració de sistemes informàtics en xarxa', 'parent_id' => 156],
    ['name' => 'ICA1 - Administració de sistemes informàtics en xarxa (ciberseguretat)', 'parent_id' => 156],
    ['name' => 'ICB0 - Desenvolupament d\'aplicacions multiplataforma', 'parent_id' => 156],
    ['name' => 'ICB1 - Desenvolupament d\'aplicacions multiplataforma (informàtica aplicada a la logística)', 'parent_id' => 156],
    ['name' => 'ICB2 - Desenvolupament d\'aplicacions multiplataforma (videojocs i oci digital)', 'parent_id' => 156],
    ['name' => 'ICC0 - Desenvolupament d\'aplicacions web', 'parent_id' => 156],
    ['name' => 'ICC1 - Desenvolupament d\'aplicacions web (bioinformàtica)', 'parent_id' => 156],
    
    ['name' => 'IM - Instal·lació i Manteniment', 'parent_id' => 2],
    ['name' => 'IMA0 - Manteniment d\'instal·lacions tèrmiques i de fluids', 'parent_id' => 164],
    ['name' => 'IMB0 - Desenvolupament de projectes d\'instal·lacions tèrmiques i de fluids', 'parent_id' => 164],
    ['name' => 'IMC0 - Mecatrònica industrial', 'parent_id' => 164],
    ['name' => 'IMC1 - Mecatrònica industrial (fabricació de productes ceràmics)', 'parent_id' => 164],
    
    ['name' => 'IP - Imatge Personal', 'parent_id' => 2],
    ['name' => 'IPA0 - Assessoria d\'imatge personal i corporativa', 'parent_id' => 169],
    ['name' => 'IPB0 - Estètica integral i benestar', 'parent_id' => 169],
    ['name' => 'IPC0 - Estilisme i direcció de perruqueria', 'parent_id' => 169],
    ['name' => 'IPD0 - Caracterització i maquillatge professional', 'parent_id' => 169],
    
    ['name' => 'IS - Imatge i So', 'parent_id' => 2],
    ['name' => 'ISA0 - Realització de projectes d\'audiovisuals i espectacles', 'parent_id' => 174],
    ['name' => 'ISB0 - Il·luminació, captació i tractament d\'imatge', 'parent_id' => 174],
    ['name' => 'ISC0 - So per a audiovisuals i espectacles', 'parent_id' => 174],
    ['name' => 'ISD0 - Producció d\'audiovisuals i espectacles', 'parent_id' => 174],
    ['name' => 'ISE0 - Animacions 3D, jocs i entorns interactius', 'parent_id' => 174],
    ['name' => 'ISE1 - Animacions 3D, jocs i entorns interactius (móns virtuals, realitat augmentada i gamificació)', 'parent_id' => 174],
    
    ['name' => 'MP - Marítim-Pesquera', 'parent_id' => 2],
    ['name' => 'MPA0 - Transport marítim i pesca d\'altura', 'parent_id' => 181],
    ['name' => 'MPB0 - Aqüicultura', 'parent_id' => 181],
    ['name' => 'MPC0 - Organització del manteniment de la maquinària de vaixells i embarcacions', 'parent_id' => 181],
    
    ['name' => 'QU - Química', 'parent_id' => 2],
    ['name' => 'QUA0 - Química industrial', 'parent_id' => 185],
    ['name' => 'QUB0 - Fabricació de productes farmacèutics, biotecnològics i afins', 'parent_id' => 185],
    ['name' => 'QUD0 - Laboratori d\'anàlisi i control de qualitat', 'parent_id' => 185],
    
    ['name' => 'SA - Sanitat', 'parent_id' => 2],
    ['name' => 'SAA0 - Pròtesis dentals', 'parent_id' => 189],
    ['name' => 'SAB0 - Ortopròtesi i productes de suport', 'parent_id' => 189],
    ['name' => 'SAC0 - Anatomia patològica i citodiagnòstic', 'parent_id' => 189],
    ['name' => 'SAD0 - Documentació i administració sanitària', 'parent_id' => 189],
    ['name' => 'SAD1 - Documentació i administració sanitàries (gestió de dades)', 'parent_id' => 189],
    ['name' => 'SAE0 - Laboratori clínic i biomèdic', 'parent_id' => 189],
    ['name' => 'SAE1 - Laboratori clínic i biomèdic (recerca)', 'parent_id' => 189],
    ['name' => 'SAF0 - Radioteràpia i dosimetria', 'parent_id' => 189],
    ['name' => 'SAG0 - Audiologia protètica', 'parent_id' => 189],
    ['name' => 'SAH0 - Higiene bucodental', 'parent_id' => 189],
    ['name' => 'SAI0 - Imatge per al diagnòstic i medicina nuclear', 'parent_id' => 189],
    
    ['name' => 'SC - Serveis Socioculturals', 'parent_id' => 2],
    ['name' => 'SCA0 - Animació sociocultural i turística', 'parent_id' => 201],
    ['name' => 'SCB0 - Educació Infantil', 'parent_id' => 201],
    ['name' => 'SCC0 - Integració social', 'parent_id' => 201],
    ['name' => 'SCD0 - Promoció d\'igualtat de gènere', 'parent_id' => 201],
    ['name' => 'SCE0 - Mediació comunicativa', 'parent_id' => 201],
    
    ['name' => 'SM - Seguretat i Medi Ambient', 'parent_id' => 2],
    ['name' => 'SMA0 - Educació i control ambiental', 'parent_id' => 207],
    ['name' => 'SMB0 - Coordinació d\'emergències i protecció civil', 'parent_id' => 207],
    
    ['name' => 'TM - Transport i Manteniment de Vehicles', 'parent_id' => 2],
    ['name' => 'TMA0 - Automoció', 'parent_id' => 210],
    ['name' => 'TMA1 - Automoció (Vehicles industrials)', 'parent_id' => 210],
    
    ['name' => 'TX - Tèxtil i Confecció', 'parent_id' => 2],
    ['name' => 'TXA0 - Disseny tècnic en tèxtil i pell', 'parent_id' => 213],
    ['name' => 'TXB0 - Vestuari a mida i d\'espectacles', 'parent_id' => 213],
    ['name' => 'TXE0 - Patronatge i moda', 'parent_id' => 213]
];
?>